javascript-tutorial/it.javascript.info

1-js/11-async/02-promise-basics/01-re-resolve/solution.md
1-js/11-async/02-promise-basics/01-re-resolve/task.md
1-js/11-async/02-promise-basics/02-delay-promise/solution.md
1-js/11-async/02-promise-basics/article.md

11-async/02-promise-basics

---

9-regular-expressions/01-regexp-introduction/article.md

Translated patterns and flags article #1

Patterns and Flags

---

9-regular-expressions/20-regexp-unicode/article.md
9-regular-expressions/21-regexp-unicode-properties/article.md

#1  Translated chapter 20: regexp unicode and chapter 21: regexp unicode properties.

Unicode: flag "u" and class \p{...}

---

1-js/13-modules/01-modules-intro/article.md
1-js/13-modules/01-modules-intro/say.view/say.js
1-js/13-modules/01-modules-intro/scopes.view/hello.js
1-js/13-modules/index.md

Translated chapter: Modules Introduction #1

Modules, introduction

---

9-regular-expressions/12-regexp-anchors/1-start-end/solution.md
9-regular-expressions/12-regexp-anchors/1-start-end/task.md
9-regular-expressions/12-regexp-anchors/2-test-mac/solution.md
9-regular-expressions/12-regexp-anchors/2-test-mac/task.md
9-regular-expressions/12-regexp-anchors/article.md

Translated article and exercises for #1

Anchors: string start ^ and end $

---

README.md

Some examples were in Italian and some in Spanish. 
Some comments were in Italian and some in English.

Consistency of examples

---

5-network/01-fetch/01-fetch-users/_js.view/source.js
5-network/01-fetch/01-fetch-users/solution.md
5-network/01-fetch/01-fetch-users/task.md
5-network/01-fetch/article.md

I translated the chapter and the tests.
I hope it's good!

translated chapter 3.3.1: fetch

---

1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/solution.md
1-js/06-advanced-functions/08-settimeout-setinterval/1-output-numbers-100ms/task.md
1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/solution.md
1-js/06-advanced-functions/08-settimeout-setinterval/4-settimeout-result/task.md
1-js/06-advanced-functions/08-settimeout-setinterval/article.md

Traduzione in italiano completa di esercizi

Scheduling: setTimeout and setInterval 

---

1-js/02-first-steps/11-logical-operators/article.md

Sistemato qualche errore grammaticale e la struttura di un paio di passaggi per renderli più chiari.

errata corrige in 'Operatori Logici'

---

1-js/02-first-steps/17-arrow-functions-the-basics/article.md

Check Arrow functions, the basics

Arrow Functions, the basics

---

2-ui/99-ui-misc/03-event-loop/article.md

Pierangelomiceli patch 1

---

1-js/10-error-handling/1-try-catch/article.md

After the issue 119, I reread the article I had translated and noticed several spelling errors. I have therefore made the necessary corrections

Correction of some spelling and grammatical errors

---

1-js/01-getting-started/1-intro/article.md
1-js/01-getting-started/2-manuals-specifications/article.md

Translated article 01-getting-started/2-manuals-specifications.
Approving checklist:

Translated 01-getting-started/2-manuals-specifications

---

1-js/01-getting-started/4-devtools/article.md

Rivisto l'articolo già tradotto, apportare solo piccole modifiche per rendere la traduzione dall'inglese meno "letterale" e più scorrevole.

Articolo 01/4-devtools rivisto e corretto

---

1-js/02-first-steps/01-hello-world/1-hello-alert/task.md
1-js/02-first-steps/01-hello-world/article.md

Reviewed "Hello World" article. The section "La segnatura moderna" it's changed a little bit, so give a deeper look at it.

Hello, world!

---

1-js/02-first-steps/02-structure/article.md

Reviewed "Code structure" article.

Code structure

---

1-js/02-first-steps/09-comparison/1-comparison-questions/solution.md
1-js/02-first-steps/09-comparison/1-comparison-questions/task.md
1-js/02-first-steps/09-comparison/article.md

Sincronizzato anche l'articolo con alcuni piccoli aggiornamenti della versione inglese.

Corretto ed aggiornato articolo ed esercizi 02/09-comparison

---

1-js/03-code-quality/02-coding-style/article.md

Review e aggiornamento dell'articolo Coding Style

Coding Style

---

1-js/01-getting-started/3-code-editors/article.md

Ciao ragazzi, date un'occhiata a questa revisione per favore. Tra le modifiche principali, ho pensato di cambiare multi-piattaforma direttamente in *cross-platform*; sempre nell'ottica di familiarizzare il lettore italiano con i termini tecnici in inglese. 
Potete dirmi se ho proceduto correttamente alla richiesta di merging? Se ho editato nella mia versione e richiesto correttamente il merging con quella 'ufficiale'

Revisione terzo articolo.

---

CONTRIBUTING.md

Ho aggiornato leggermente la parte di contribuzione per principianti, cercando di esplicitare il più possibile la metodologia di prenotazione degli articoli

updated CONTRIBUTING

---

2-ui/2-events/01-introduction-browser-events/01-hide-other/task.md
2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/solution.md
2-ui/2-events/01-introduction-browser-events/02-hide-self-onclick/task.md
2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/solution.md
2-ui/2-events/01-introduction-browser-events/03-which-handlers-run/task.md
2-ui/2-events/01-introduction-browser-events/04-move-ball-field/solution.md
2-ui/2-events/01-introduction-browser-events/04-move-ball-field/task.md
2-ui/2-events/01-introduction-browser-events/05-sliding-menu/solution.md
2-ui/2-events/01-introduction-browser-events/05-sliding-menu/task.md
2-ui/2-events/01-introduction-browser-events/06-hide-message/solution.md
2-ui/2-events/01-introduction-browser-events/06-hide-message/task.md
2-ui/2-events/01-introduction-browser-events/07-carousel/solution.md
2-ui/2-events/01-introduction-browser-events/07-carousel/task.md

Ci sono delle N.d.T esaustive, vedere quali mantenere

Introduction to browser events

---

1-js/02-first-steps/16-function-expressions/article.md

Articolo sulle espressioni di funzione

articolo function expressions

---

1-js/04-object-basics/09-object-toprimitive/article.md

objects to primitive conversion

revisione articolo objects to primitive conversion

---

1-js/04-object-basics/06-constructor-new/1-two-functions-one-object/solution.md
1-js/04-object-basics/06-constructor-new/article.md

new operator article

---

1-js/05-data-types/03-string/3-truncate/task.md
1-js/05-data-types/03-string/4-extract-currency/task.md
1-js/05-data-types/03-string/article.md

Review Strings

---

1-js/05-data-types/06-iterable/article.md

review iterables

---

1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
1-js/05-data-types/07-map-set/03-iterable-keys/task.md
1-js/05-data-types/07-map-set/article.md

review map-set

---

1-js/05-data-types/09-keys-values-entries/01-sum-salaries/solution.md
1-js/05-data-types/09-keys-values-entries/02-count-properties/task.md
1-js/05-data-types/09-keys-values-entries/article.md

Object.keys, values, entries

---

2-ui/1-document/01-browser-environment/article.md

Review dell'articolo ' Browser environment, specs'. Ho rimosso 3 paragrafi perché sono stati rimossi anche dalla traduzione originale

Review Browser environment, specs

---

2-ui/1-document/02-dom-nodes/article.md

Revisione dell'articolo DOM tree. 

Review DOM tree

---

2-ui/2-events/03-event-delegation/1-hide-message-delegate/source.view/index.html
2-ui/2-events/03-event-delegation/1-hide-message-delegate/task.md
2-ui/2-events/03-event-delegation/2-sliding-tree/solution.view/index.html
2-ui/2-events/03-event-delegation/2-sliding-tree/task.md
2-ui/2-events/03-event-delegation/3-sortable-table/solution.view/index.html
2-ui/2-events/03-event-delegation/3-sortable-table/source.view/index.html
2-ui/2-events/03-event-delegation/3-sortable-table/task.md
2-ui/2-events/03-event-delegation/4-behavior-tooltip/solution.view/index.html
2-ui/2-events/03-event-delegation/4-behavior-tooltip/source.view/index.html
2-ui/2-events/03-event-delegation/4-behavior-tooltip/task.md

Revisione dell'articolo Event delegation.

Review Event delegation

---

2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
2-ui/2-events/04-default-browser-action/3-image-gallery/solution.view/index.html
2-ui/2-events/04-default-browser-action/3-image-gallery/source.view/index.html
2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
2-ui/2-events/04-default-browser-action/article.md
2-ui/2-events/04-default-browser-action/menu.view/menu.js

Revisione dell'articolo Browser default actions.

Review Browser default actions

---

2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/solution.view/index.html
2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/source.view/index.html
2-ui/3-event-details/1-mouse-events-basics/01-selectable-list/task.md

Revisione dell'articolo Mouse events.

Review Mouse events

---

2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/solution.view/index.html
2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/source.view/index.html
2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md

Revisione dell'articolo Moving the mouse: mouseover/out, mouseenter/leave.

Review Moving the mouse: mouseover/out, mouseenter/leave

---

2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md

Revisione dell'articolo Drag'n'Drop with mouse events.

Review Drag'n'Drop with mouse events

---

1-js/05-data-types/05-array-methods/article.md

Errore di scrittura nel codice, che rappresenta l'esempio di Array.filter. Sia descrizione che codice erano errati con variabili inesatte

Errore di Scrittura

---

2-ui/99-ui-misc/03-event-loop/article.md

As per title, correction for a grammar error.

fix: text error correction
